function(kasane_find_llvm_clang)
  find_package(LLVM CONFIG QUIET)
  find_package(Clang CONFIG QUIET)

  if(LLVM_FOUND AND Clang_FOUND)
    message(STATUS "Kasane: found LLVM ${LLVM_PACKAGE_VERSION} and Clang tooling packages.")
    set(KASANE_LLVM_CLANG_FOUND TRUE PARENT_SCOPE)
    set(KASANE_LLVM_INCLUDE_DIRS "${LLVM_INCLUDE_DIRS}" PARENT_SCOPE)
    set(KASANE_CLANG_INCLUDE_DIRS "${CLANG_INCLUDE_DIRS}" PARENT_SCOPE)
  else()
    message(STATUS "Kasane: LLVM/Clang tooling packages not found; Clang frontend will be skipped.")
    set(KASANE_LLVM_CLANG_FOUND FALSE PARENT_SCOPE)
    set(KASANE_LLVM_INCLUDE_DIRS "" PARENT_SCOPE)
    set(KASANE_CLANG_INCLUDE_DIRS "" PARENT_SCOPE)
  endif()
endfunction()
